import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
// border-x border-slate-400
export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center bg-gradient-to-b from-[#d6b6ff9d] to-[#3842ff6c]">
        <div className="flex h-full w-full flex-col border-x-2 border-slate-200 md:max-w-2xl">
          <div className="flex items-center gap-3 border border-b-2 border-slate-200 p-4">
            <Image
              className="min-h-14 min-w-14 rounded-full blur"
              src={""}
              alt="Logo"
              height={56}
              width={56}
            />
            <input
              className="w-full bg-transparent outline-none"
              placeholder="Type some text"
            ></input>
          </div>
          <div className="flex items-center gap-3 border border-b-2 border-slate-200 p-4">
            <Image
              className="min-h-14 min-w-14 rounded-full blur"
              src={""}
              alt="Logo"
              height={56}
              width={56}
            />
            <div>
              <div>
                <span>Name</span>
                <span>{` · 6 minutes ago`}</span>
              </div>
              <span>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Hic
                consectetur fuga eius aliquid possimus, eum id expedita sint
                quas cupiditate magni, perferendis tenetur, accusamus placeat.
                Tempora hic omnis odit aliquam?
              </span>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
