import type { Post } from "@prisma/client";
import Head from "next/head";
import Image from "next/image";
// import Link from "next/link";
import { useState } from "react";
import { api } from "~/utils/api";

interface PostViewProps {
  post: Post;
}
const PostView = ({ post }: PostViewProps) => {
  return (
    <div className="flex items-center gap-3 border border-b-2 border-slate-200 p-4">
      <Image
        className="min-h-14 min-w-14 rounded-full blur"
        src={""}
        alt="Logo"
        height={56}
        width={56}
      />
      <div>
        <div>
          <span>Name</span>
          <span>{` · 6 minutes ago`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

const CreatePostWizard = () => {
  const authorId = "28f1e4f4-f9d8-4f43-85ee-37d590ad005e";
  const [input, setInput] = useState("");

  const utils = api.useUtils();

  const createPost = api.posts.create.useMutation({
    onSuccess: async () => {
      setInput("");
      await utils.posts.invalidate();
    },
  });

  return (
    <div className="flex items-center gap-3 border border-b-2 border-slate-200 p-4">
      <Image
        className="min-h-14 min-w-14 rounded-full blur"
        src={""}
        alt="Logo"
        height={56}
        width={56}
      />
      <input
        type="text"
        className="w-full bg-transparent outline-none"
        placeholder="Type some text"
        value={input}
        disabled={createPost.isPending}
        onChange={(e) => {
          setInput(e.target.value);
        }}
        onKeyDown={(e) => {
          if (input !== "" && e.key === "Enter") {
            e.preventDefault();
            createPost.mutate({ authorId, content: input });
          }
        }}
      ></input>
      {input !== "" && !createPost.isPending && (
        <button
          onClick={() => {
            createPost.mutate({ authorId, content: input });
          }}
          className="p-4"
        >
          Post
        </button>
      )}
    </div>
  );
};

export default function Home() {
  const authorId = "28f1e4f4-f9d8-4f43-85ee-37d590ad005e";
  const postsQuery = api.posts.getAll.useQuery();

  if (postsQuery.isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center bg-gradient-to-b from-[#d6b6ff9d] to-[#3842ff6c]">
        <div className="flex h-full w-full flex-col border-x-2 border-slate-200 md:max-w-2xl">
          <CreatePostWizard />
          <div className="flex grow flex-col overflow-y-scroll">
            {postsQuery.data?.map((post, index) => (
              <PostView post={post} key={index} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
